---
- name: restarted keepalived
  service:
    name: keepalived
    state: restarted

- name: locked bitwarden vault
  shell:
    cmd: "bw lock"
    executable: "/bin/bash"
  delegate_to: localhost
  check_mode: false
  changed_when: false