---
- name: Loaded kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ kernel_modules }}"
- name: sysctl setting
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    sysctl_file: "/etc/sysctl.d/k8s_{{ hostname }}.conf"
  with_items: "{{ sysctl_settings }}"
