---
- name: Restarted ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Locked bitwarden vault
  ansible.builtin.shell:
    cmd: "bw lock"
    executable: "/bin/bash"
  delegate_to: localhost
  become: false
  check_mode: false
  changed_when: false
