---
- name: Restarted unattended-upgrade services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - unattended-upgrades
    - apt-daily.timer
    - apt-daily-upgrade.timer

- name: Restarted ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Locked bitwarden vault
  ansible.builtin.shell:
    cmd: "bw lock"
    executable: "/bin/bash"
  delegate_to: localhost
  become: false
  check_mode: false
  changed_when: false
