---
- name: restarted unattended-upgrade services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - unattended-upgrades
    - apt-daily.timer
    - apt-daily-upgrade.timer

- name: restarted ssh
  service:
    name: ssh
    state: restarted

- name: locked bitwarden vault
  shell:
    cmd: "bw lock"
    executable: "/bin/bash"
  delegate_to: localhost
  check_mode: false
