---
- name: restarted untended-upgrade services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - restart unattended-upgrades
    - restart apt-daily.timer
    - restart apt-daily-upgrade.timer

- name: restarted ssh
  service:
    name: ssh
    state: restarted
