---
- name: Installed haproxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Prepared haproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restarted haproxy
