---
lb:
  vip: 192.168.0.227

haproxy:
  bind: "{{ lb.vip }}"
  servers:
    - name: "master-01-rke2-server-ubuntu-24-04-home-amd64"
      ip: 192.168.0.126
    - name: "master-02-rke2-server-ubuntu-24-04-home-amd64"
      ip: 192.168.0.127
    - name: "master-03-rke2-server-ubuntu-24-04-home-amd64"
      ip: 192.168.0.128

bw_cred_keepalived: '24a0a201-19de-4475-94bc-b2e800eb387a'
bw_cred_rke2_server_token: 'bc5460f9-2ed0-417b-a8ba-b2ea00ff40eb'
