---
- name: Create config dir
  become: true
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Create cluster config file
  become: true
  template:
    src: rke2_config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restarted rke2-server
