---
- name: Get RKE2 server token for agent nodes
  hosts: rke2-server-primary
  strategy: debug
  gather_facts: true
  become: true
  vars:
    ansible_user: miutaku
  tasks:
    - name: Read RKE2 server token
      ansible.builtin.slurp:
        src: /var/lib/rancher/rke2/server/token
      register: rke2_token_raw
      tags: rke2_agent_node
      when: not ansible_check_mode

    - name: Set dummy token
      ansible.builtin.set_fact:
        rke2_token_raw:
          content: "{{ 'dummy_token' | b64encode }}"
      when: ansible_check_mode

    - name: Set token fact for all hosts
      ansible.builtin.set_fact:
        rke2_node_token: "{{ rke2_token_raw.content | b64decode }}"
      delegate_to: localhost
      tags: rke2_agent_node

    - name: Add token fact to all agent hosts
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: rke2-agent
        rke2_node_token: "{{ rke2_token_raw.content | b64decode }}"
      loop: "{{ groups['rke2-agent'] }}"
      changed_when: false
      tags: rke2_agent_node

- name: Configure RKE2 Agent Nodes
  hosts: rke2-agent
  strategy: debug
  gather_facts: true
  become: true
  vars:
    ansible_user: miutaku
    rke2_node_token: "{{ hostvars[inventory_hostname].rke2_node_token }}"
  roles:
    - role: common
      tags: common
    - role: rke2_agent_node
      tags: rke2_agent_node
    - role: rke2_all_node
      tags: rke2_all_node

- name: Finalized
  hosts: rke2-agent
  gather_facts: false
  become: true
  vars:
    ansible_user: miutaku
    rke2_node_token: "{{ hostvars[inventory_hostname].rke2_node_token }}"
  roles:
    - role: auto_update
      tags: auto_update
