---
- name: Configure common settings for RKE2 Server Nodes
  hosts: rke2-server
  strategy: debug
  gather_facts: true
  become: true
  vars:
    ansible_user: miutaku # tips: with --ask-become-pass, this user must have sudo privileges
  roles:
    - role: common
      tags: common
    - role: sysctl
      tags: sysctl
    - role: rke2/server_node
      tags: rke2_server
    - role: rke2/all_node
      tags: rke2_all_node
