---
- name: Configure Load Balancer for RKE2 Server Nodes
  hosts: rke2-lb
  strategy: debug
  gather_facts: true
  become: true
  vars:
    ansible_user: miutaku # tips: with --ask-become-pass, this user must have sudo privileges
  roles:
    - role: common
      tags: common
    - role: sysctl
      tags: sysctl
    - role: keepalived
      tags: keepalived
    - role: haproxy
      tags: haproxy
    - role: auto_update
      tags: auto_update
