---
- name: installed keepalived
  apt:
    name: keepalived
    state: present
    update_cache: true

- name: Unlocked bitwarden vault with generated session key
  shell:
    cmd: "bw unlock {{ bw_passwd }} --raw"
    executable: "/bin/bash"
  environment:
    PATH: "{{ lookup('env', 'PATH') }}"
  delegate_to: localhost
  register: bw_session_key
  check_mode: false
  changed_when: false
  notify:
    - locked bitwarden vault

- name: get keepalived auth_pass from bitwarden
  shell:
    cmd: "bw get item {{ bw_credentials.keepalived }} --session {{ bw_session_key.stdout }} | jq -r .login.password"
    executable: "/bin/bash"
  delegate_to: localhost
  register: keepalived_auth_pass
  check_mode: false
  changed_when: false

- name: prepared keepalived configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restared keepalived
