---
- name: Restarted haproxy
  service:
    name: haproxy
    state: restarted

- name: Locked bitwarden vault
  shell:
    cmd: "bw lock"
    executable: "/bin/bash"
  delegate_to: localhost
  check_mode: false
  changed_when: false
