---
- name: Restarted haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  when: not (install_haproxy.changed == true and ansible_check_mode == true)

- name: Locked bitwarden vault
  ansible.builtin.shell:
    cmd: "bw lock"
    executable: "/bin/bash"
  delegate_to: localhost
  check_mode: false
  changed_when: false
