---
- name: Started first master
  become: true
  ansible.builtin.service:
    name: rke2-server
    state: started
    enabled: true

- name: Read RKE2 server token
  ansible.builtin.slurp:
    src: /var/lib/rancher/rke2/server/token
  register: rke2_token

- name: Set cluster facts on localhost
  set_fact:
    rke2_node_token: "{{ rke2_token.content | b64decode }}"

- name: Share rke2_node_token with all hosts
  add_host:
    name: "rke2_token_holder"
    rke2_node_token: "{{ rke2_node_token }}"
    groups: shared_token
  delegate_to: localhost
  run_once: true
