---
name: Notify private repo

on:
  push:
    branches:
      - dev
      - stg
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify private repo
        run: |
          curl -X POST https://api.github.com/repos/${{ github.actor }}/${{ secrets.PRIVATE_DEPLOY_REPO }}/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PRIVATE_RKE2_REPO_PAT }}" \
            -d '{"event_type":"deploy_from_public_repo", "client_payload": { "branch": "${{ github.ref_name }}" }}'
